### ISSUE TITLE
Different names for the same malware? 

### ISSUE THREAD

**Issue by Rafiot** [Te-k/stalkerware-indicators#2]
https://github.com/Te-k/stalkerware-indicators/blob/eb832dcec7677adf739e73845dae285c3c8fd1cd/appid.yaml#L22
and 
https://github.com/Te-k/stalkerware-indicators/blob/eb832dcec7677adf739e73845dae285c3c8fd1cd/appid.yaml#L54

The name without a space it used everywhere except for the 1st link above.

**Comment by Te-k** [comment]
Thanks, I just fixed that
