### ISSUE TITLE
A couple of missing ones

### ISSUE THREAD

**Issue by jvoisin** [Te-k/stalkerware-indicators#20]
I currently don't have samples for all of them unfortunately.

- antifurtodroid.com
  - #31
- [callsmstracker.com]( https://play.google.com/store/apps/details?id=com.gcm_call_sms_tracker.updated)
  - #32
- aispyer.com
  - #33
- [androidlost.com]( https://play.google.com/store/apps/details?id=com.androidlost)
- [asgardtech.ru](https://play.google.com/store/apps/details?id=com.mobile.asgard)
- a-spy.com
  - [samples]( https://www.virustotal.com/gui/search/%2522a-spy.com%2522/files)
- blurspy.com
  - #36
- coupletracker.com
  - [latest sample]( https://coupletracker.com/download-apk/)
  - #37
- [easyphonetrack.com]( https://www.virustotal.com/gui/file/c9f727d24e1c692c9b66176e9521b95bd39343b5abbeff5cd37544764c5b9bed?nocache=1)
  - [latest version]( https://easyphonetrack.com/parental_control/download)
  - #30
- evaspy.com
  - `8CA3D60AD8FD3584370ACFADDFC29979F25D57D3` isn't on VT
- [eyezy.com]( https://www.virustotal.com/gui/file/923dfbc6f0291a4918429503deaab988a6802cd3532b4819691ba9c74a0e6856 )
  - [download url]( https://q12z.net/) 
  - [latest sample]( https://www.virustotal.com/gui/file/91a38c26ab2a125e0bdde294834b570ebe7454c1c6ffd0be47454c80d5a7f5f5?nocache=1)
  - #27
- freespy / spyzee.com
  - Rebrand of TruthSpy?
- fonemonitor.co
  - #38
- myfonemate.com
  - [Sample]( https://www.virustotal.com/gui/file/570e2036e58885b33ae57125db89f08a8645565a4ec9ca9306d8b99570062e47/detection )
  - Rebrand of mSpy
  - #39
- mobilespy.at
  - Rebrand of Asgardtech malwares?
- ownspy.com
  - #40
- sap4mobile.com
  - #41
- [spappmonitoring.com](https://www.virustotal.com/gui/file/ce565b96e1f709ed65c7b7a034eb0ef2440a2b015fdcb3003c9bfae438f23aca)
- [spycell.net](https://www.virustotal.com/gui/file/201625b0ab47027bd2dcb27f88c5c0cf96e4bc32505083cb7036639c6a4a8b24)
- spyphone.com / spyfone.com
- [spytoapp.com]( https://www.virustotal.com/gui/file/77cee7c7c27f19137da5fbf949e6d9bc3acaa1fb462e6a69125da8934744e45d )
  - #35
- [spytrac.com](https://www.virustotal.com/gui/file/a93959574b257f23cb05b987ced67968e3de67080f17f34a516010fce9a54cd3?nocache=1) and its [keylogger]( https://www.virustotal.com/gui/file/42c8b1ecc6d2928cff2206c1a7d5ab6360767ea8d75aa5dc837f9c58cf81e38c?nocache=1)
- teensafe.net
- [tispy.net](https://www.virustotal.com/gui/file/10ce85225db353492f7db4f09dc77047a5879949fcb65806079c7e0d769fd3c1?nocache=1 )
- thewispy.com
- theispyoo.com / myfonemate.com / freefonespy.com
- [spyera.com](https://github.com/Te-k/stalkerware-indicators/files/8455402/bbcc2beeeb32c65a6d4be4af7f2c5c420862b4842cf92c00055b11136c162527.zip)
  - #24 #25 #26

**Comment by Te-k** [comment]
Thanks, I'll try to find some

**Comment by Te-k** [comment]
Thanks a lot ! I have merged most of them and added you in the list of contributors
