### ISSUE TITLE
[Contribution] Package name for Snoopza

### ISSUE THREAD

**Issue by leandreSL** [Te-k/stalkerware-indicators#6]
Hi,
I discovered a new package name for Snoopza app : `com.android.core.mngp` . 
Apparently, they use the same pattern to name their application : com.android.core.mng*.

VT analysis : https://www.virustotal.com/gui/file/8ceccb0637ecb2ebe90a96ea63e99603be67e4e4e20b2195c69feef633136558/detection 

Have a good day,
Léandre

**Comment by Te-k** [comment]
I just added it to the repository, merci !
