### ISSUE TITLE
Linter

### ISSUE THREAD

**Issue by Te-k** [Te-k/stalkerware-indicators#64]
Add scripts to:
- [x] check formatting
- [x] check that the YAML keys are coherent (`website` instead of domain`, missing `tag`, …)
- [x] warn on duplicates
- [x] check that stalkerware names in the IOC are present in the [README]( https://github.com/Te-k/stalkerware-indicators#stalkerware ) as well

**Comment by jvoisin** [comment]
It would also be neat to check that stalkerware names used in IOC are present in [the readme]( https://github.com/Te-k/stalkerware-indicators#stalkerware) as well.
