### ISSUE TITLE
A bunch of new indicators

### ISSUE THREAD

**Issue by U039b** [Te-k/stalkerware-indicators#7]
Hi @Te-k and thank you for your awesome work.
By taking your indicators (list of hosts, IPs) as input, I scripted a search on ApkLab and have extracted both packages and certificates of apps communicating with specified hosts. 

Here is the [JSON dump](https://paste.0x39b.fr/?a0df7b7c65aeea24#B15QMBJ2As98HR8iDZDxySuNqNUyq4rG1cDjWQKvZyG5).

**Comment by Te-k** [comment]
Thanks !

**Comment by T145** [comment]
To this point, having a `network.json` over `network.csv` format would make information processing easier. I'd still have separate sections for `ips` and `domains` over a single `hosts` field.
