### ISSUE TITLE
Decide what we want to do with regard to websites vs. C2

### ISSUE THREAD

**Issue by jvoisin** [Te-k/stalkerware-indicators#70]
Currently, we're tracking different things network-wise:

- C2
- Websites
- C2 that are also Websites
- IP Addresses, that are C2, websites, and sometimes both

Are we ok with this state of affairs? Either way, we should document what we're tracking network-wise, to avoid surprising netops/partners/users/…

Tasks : 

- [x] Update the README to clarify what we consider stalkerware
- [x] Update the README to clarify what we include in network indicators and different files
- [x] Migrate network.csv to network.yml
- [x] Include information on C2/website in network.yml
- [x] Update generation scripts, include a network.csv file for readability

**Comment by U039b** [comment]
If we stick to the definition of *stalkerware* proposed by the [Coalition Against Stalkerware](https://stopstalkerware.org/), a stalkerware is a software offering a precise set of features.

> Stalkerware refers to tools – software programs, apps and devices – that enable someone to secretly spy on another person’s private life via their mobile device. The abuser can remotely monitor the whole device including web searches, geolocation, text messages, photos, voice calls and much more. 

So, for me, we should list all softwares fitting with the definition above without making any distinction between software meant to spy on partner or meant to spy on employees.

**Comment by U039b** [comment]
I think that there is no universal answer to that question. We list indicators and people using those listings are free to choose what to block. In the CSV file, we can add another column explaining the purpose of each indicator such as *Website*,  *Agent*,  *C2*. If a domain serves as both website and C2, we tag it as C2.

**Comment by Te-k** [comment]
Sounds good, so : 

* We take a broad definition of stalkerware 
* We need to clarify what is C2 and domain in network.csv (and make it a YAML file)

I have added a list of tasks to the ticket, I can work on it this week-end

**Comment by Te-k** [comment]
One last question to solve is : which types of network indicator do we include in each IOC file? So far I have limited suricata and host file to C2 only
