### ISSUE TITLE
Check the coverage of various reports

### ISSUE THREAD

**Issue by jvoisin** [Te-k/stalkerware-indicators#71]
Check the IOC of:

- [x] [ESET 2021]( https://www.eset.com/fileadmin/ESET/CZ/Blog/2021/ESET_Android_stalkerware_vulnerabilities_white_paper.pdf)
- [x] [Citizenlab 2019]( https://citizenlab.ca/docs/stalkerware-holistic.pdf )
- [x] [Kaspersky 2021]( https://media.kasperskycontenthub.com/wp-content/uploads/sites/43/2022/04/12075509/EN_The-State-of-Stalkerware-2021.pdf)

**Comment by Te-k** [comment]
Nothing in the Kaspersky report except the mention of wSpy, not sure if they mean ShadowSpy or if it is another app
