### ISSUE TITLE
Adding new IOCs

### ISSUE THREAD

**Issue by WanderingCoder-Omen** [Te-k/stalkerware-indicators#76]
Hiya @Te-k and thank you for this amazing repo that you guys have put together and are constantly maintaining. I have a few malicious Android stalkerware APKs how do I add it to the IOCs in any of the formats that are there in the generated folder.

**Comment by Te-k** [comment]
Hi ! 
Here is what you need to do : 
* Fork the repo and clone it
* Analyse the APKs, see what stalkerware it is, the certificate, package name and domain it uses and add them to the file [ioc.yaml](https://github.com/Te-k/stalkerware-indicators/blob/master/ioc.yaml)
* Add the samples to [the list of samples](https://github.com/Te-k/stalkerware-indicators/blob/master/samples.csv) (you can use [this script](https://github.com/Te-k/stalkerware-indicators/blob/master/scripts/add_sample.py)
* Commit, push and do a Pull Request

Let me know if anything is not clear in the format or if you have any questions

**Comment by WanderingCoder-Omen** [comment]
Awesome..will get onto it. Thanks a ton !
